
#访问根路径

#应用名称
spring:
  application:
    name: springboot-demo
#    数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/network?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: wjx990717
#    热启动
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
#  mail
  mail:
    host: smtp.qq.com
    port: 465
    username: lamaxiyafc@qq.com
    password: lwqgpgluriqmddci
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
      debug: true
#  security:
#    user:
#      name: root
#      password: root
#      roles: admin
  #访问端口号
server:
  port: 9999
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 30m
  #mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.themeleaf.entity

#logging:
#  level:
#    com.shimain.springboot.mapper: DEBUG
